name: Code Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container: oven/bun:latest

    services:
      mongodb:
        image: mongodb/mongodb-community-server:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint code
        run: bun run lint

      - name: Create mongoDB Docker container
        run: sudo docker run -d -p 27017:27017 mongo:latest

      - name: Test the code
        run: bun test
        env:
          DB_URI: mongodb://mongodb:27017/shadow-accounts
