name: Build Image

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  test:
    uses: leanderpaul/shadow-accounts-service/.github/workflows/code-test.yml@master

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun runtime
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.x

      - name: Build app
        run: bun run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app
          retention-days: 7
          path: |
            dist
            Dockerfile

  publish:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      digest: ${{ steps.docker-build.outputs.digest }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Download production artifacts
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: docker-build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
