name: Code Test

on:
  workflow_call:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    services:
      mongodb:
        image: mongodb/mongodb-community-server:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun runtime
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.x

      - name: Install dependencies
        run: bun install --frozen-lockfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint code
        run: bun run lint

      - name: Test the code
        run: bun test
        env:
          DB_URI: mongodb://localhost/shadow-accounts
